const maps = require('./maps')
const queue = require('./queue')
const stack = require('./stack')
const minDeletions = require('./min-deletion-frequency')

maps()
console.log('************************************')
queue()
console.log('************************************')
stack()
console.log('************************************')
minDeletions("aaabbbcc")